[package]
name = "color-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
env_logger = { version = "0.11.3", default-features = false }
log = "0.4.21"
